[package]
name = "glicol_parser"
version = "0.10.0"
authors = ["chaosprint <chaosprint@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
glicol_macros = {path = "../macros"}
glicol_synth = {path = "../synth"}
hashbrown = "0.12"